### ISSUE TITLE
Ugly Ui

### ISSUE THREAD

**Issue by pioncz** [Mytherin/Tibialyzer#1]
Hello,
Ui looks a bit like 90's so i create this issue and i will contribute to help you! :dancer: 
Cheers bro, cool idea with this stuff.

**Comment by Mytherin** [comment]
While subjective, I believe this has been resolved by [this commit.](https://github.com/Mytherin/Tibialyzer/commit/616a315ddf6ce34a498658958a0fbe49ee760119)
