### ISSUE TITLE
Building version from 15.02

### ISSUE THREAD

**Issue by pioncz** [Mytherin/Tibialyzer#10]
Hello,
I've tried to build newest version from your build and i saw several errors, last one i couldn't handle myself.

- After double click on mainform i got some errors with your custom controls (ignoring them probably solved issue)
- There was simple problem with null pointer exception, solved by wraping it in if statement
- MainForm.cs Line 723: this.popupAnimationBox.Checked = SettingsManager.getSettingBool("EnableSimpleNotificationAnimation");
this.popupAnimationBox appears to be null

I don't know how to add them so they will be visible to Visual Studio

**Comment by Mytherin** [comment]
I just downloaded the source zip and compiled it myself and I have none of these issues, which version of Visual Studio are you using?

**Comment by pioncz** [comment]
Okay, i've downloaded once again and it builds.
I have Visual Studio Community 2015 if you still wants to know :)
