### ISSUE TITLE
Zip file without .exe

### ISSUE THREAD

**Issue by starscd** [Mytherin/Tibialyzer#102]
Hi guys, i'm just trying to start using Tibialyzer, but when i download it from here the zip file don't had the .exe file, how can i start Tibialyzer without that?

Kind regards

**Comment by KuerbisGnu** [comment]
Maybe you are downloaded the source code. Try to download the latest release.
https://github.com/Mytherin/Tibialyzer/releases/download/1.3.0/Tibialyzer.v1.3.0.zip
