### ISSUE TITLE
Task counter

### ISSUE THREAD

**Issue by Lutheine** [Mytherin/Tibialyzer#104]
Hey 
How about adding counter that counts total mobs of task from tracked creatures menu. For an example instead having X mob a, Y mob b and Z mob c, it would display total number of killed of tracking mobs

**Comment by vinilodeon** [comment]
it would be awesome

**Comment by Mytherin** [comment]
Added in 88b3c3d76da4f994fe2d37ba7e0f5b4354175fe6.
