### ISSUE TITLE
Possible to remove loot or waste?

### ISSUE THREAD

**Issue by Vinibi** [Mytherin/Tibialyzer#107]
Hello guys,

There're two interesting commands: "addloot" and "addwaste"

I wonder if there're commands to "remove loot" and "remove waste"...

Thank you

**Comment by Mytherin** [comment]
You can use the `delete` command to delete specific kills you have made (e.g. delete@[creature] or delete@[killcount], see [here](https://github.com/Mytherin/Tibialyzer/wiki/Settings-Guide#additional-loot-management-tips)).

You can also try to use `addloot@` and `addwaste@` with negative counts, i.e. `addloot@[item]@-10`. Not sure if that will work correctly, though.

**Comment by Vinibi** [comment]
Thanks Mark,

Using a negative sighal worked properly.

Thank you again.
