### ISSUE TITLE
Suggestion Browse NPC

### ISSUE THREAD

**Issue by fernandorahn** [Mytherin/Tibialyzer#109]
I think the function browser NPC name is not useful, most of players don't know the names of the NPCs to search for it, maybe you can change it to browse a NPC of X service, NPC who sell potions, boat npcs and more.

Sorry if this isn't the right place to post it.

Tibialyzer is a wonderful program, great job.

**Comment by KuerbisGnu** [comment]
All this is already included. You can find the boat by city@ command.
You can find the Magic Store when you use item@ command.
You can easily find the name of any shopkeeper in Tibia.

**Comment by Mytherin** [comment]
To add to what KuerbisGnu said, you can use the command `[cityname]@[itemname]` to find an NPC that buys or sells a specific item in a specific city; so if you want to find the item that sells mana potions in edron you can type `edron@mana potion`.
