### ISSUE TITLE
Used items

### ISSUE THREAD

**Issue by sebbanx** [Mytherin/Tibialyzer#110]
My Tibialyzer is no longer adding ammo to the used items in the summary/waste form. I've updated it to the newest version, but it's still ain't showing up. Has it been removed, or is there something im missing?

**Comment by Mytherin** [comment]
Try updating your memory addresses by clicking [this button](http://i.imgur.com/npIRVrt.png) (or updating them manually).

**Comment by sebbanx** [comment]
All-right, thanks for the fast response!
I believe that solved it, It seems to be working for the time beeing.
