### ISSUE TITLE
route not working

### ISSUE THREAD

**Issue by CladesAffero** [Mytherin/Tibialyzer#117]
while on windows 10, and using 1.3.0 all functions works perfectly except for routes. it displays the following
https://i.gyazo.com/d7a14f8686e63d314c3270ac6dcb0cc0.png

**Comment by mooop12** [comment]
+1, I'm pretty sure it worked in 10.97 and stopped working on 10.98, at least for me.

**Comment by patchido** [comment]
this happens to me too at 1.4.2 running tibia 11 windows 10
