### ISSUE TITLE
Use semver (i.e. vX.Y.Z) for versioning

### ISSUE THREAD

**Issue by mathiasbynens** [Mytherin/Tibialyzer#12]
Please consider using [the semver versioning scheme](http://semver.org/)? Following semver, the initial release was 1.0.0 (not “1.0”), and the latest version 1.1.0 (rather than “1.1”).

No big deal either way but it would be nice to make sense of the version numbers.

**Comment by Mytherin** [comment]
Alright, I modified the version number. Good suggestion.

**Comment by mathiasbynens** [comment]
Hurray for meaningful version numbers! :+1:
