### ISSUE TITLE
Rings and Amulets dont get calculated in waste

### ISSUE THREAD

**Issue by oufooz** [Mytherin/Tibialyzer#120]
title say's it all.

**Comment by Galarzaa90** [comment]
The main problem here is knowing the difference between the amulet/ring running out and the player taking it off.

If I remember correctly, if you take just 1 arrow out of your arrow slot, Tibialyzer will count it as a wasted arrow.

**Comment by oufooz** [comment]
well .. i cant even see the arrows in waste

**Comment by KuerbisGnu** [comment]
Try to update your memory addresses.
[This Button](http://i.imgur.com/npIRVrt.png)
