### ISSUE TITLE
Show loot window for certain items that are below X gold

### ISSUE THREAD

**Issue by nickbrisola** [Mytherin/Tibialyzer#122]
hey, sometime I miss some items like life rings and such that aren't shown because they are below the 2k cap that I've set. Can I make some exception for certain itens to open a loot window?
thanks

**Comment by CladesAffero** [comment]
yes you can, it's within the same tab where you set up the 2k cap. https://github.com/Mytherin/Tibialyzer/wiki/Settings-Guide#popups-tab
