### ISSUE TITLE
autohotkey doesn't work propertly with shift

### ISSUE THREAD

**Issue by guilhermetoti-luizalabs** [Mytherin/Tibialyzer#127]
if i bind some key with shift, eg: `shift+-::F3`, the hotkey in tibia must be on `shift+F3`, only in F3 doesn't work.

**Comment by Mytherin** [comment]
Try `Shift+-::Send {F3}`

**Comment by guilhermetoti-luizalabs** [comment]
I'll try tonight, thanks!

**Comment by guilhermetoti-luizalabs** [comment]
If it works, i close this issue!

**Comment by guilhermetoti-luizalabs** [comment]
It worked, thanks!
