### ISSUE TITLE
How to discard a specific item

### ISSUE THREAD

**Issue by Edward2103** [Mytherin/Tibialyzer#130]
Hi, im trying to understand how the database works... for example right now im trying to ignore certains loots like  the gold coins, so it doesnt count the gold coin as a loot, and i assume that i must change the item property discard from "true" to "false" but i dont know how to do it, so i will preciate if ever u can help me out!

**Comment by KuerbisGnu** [comment]
Take a look here:
https://github.com/Mytherin/Tibialyzer/wiki/Settings-Guide#database-tab

and to finetune your settings use item@[itemname]

There you can check your settings and set "Pick up" and "Convert" checkboxes.
