### ISSUE TITLE
Update today

### ISSUE THREAD

**Issue by krustzer** [Mytherin/Tibialyzer#131]
After the update the huds doesnt working properly here, this is normal?

**Comment by dodisimon** [comment]
huds and loot doesnt working here too

**Comment by mat641** [comment]
Same here. Loot not working

**Comment by KuerbisGnu** [comment]
It is normal because the adresses changes with every update.
Take a look here:
https://github.com/Mytherin/Tibialyzer/wiki/Tibia-Updated,-What-Now%3F#what-can-you-do
this solution will help you until the new adresses are available.

**Comment by Mytherin** [comment]
Should be fixed now, click "Download New Addresses" to update your memory addresses.
