### ISSUE TITLE
Tibialyzer not working with the last update

### ISSUE THREAD

**Issue by kito90** [Mytherin/Tibialyzer#133]
The curved bars and also the summary@ notification is not loading and not updating properly.

**Comment by Mytherin** [comment]
Update your memory addresses, that should fix the problem.

**Comment by kito90** [comment]
How you do that?

**Comment by Mytherin** [comment]
Click the [Download New Addresses](http://i.imgur.com/npIRVrt.png) button on the main tab.

**Comment by kito90** [comment]
q,nkhk
