### ISSUE TITLE
not an issue, but a request for utamo vita hud :D

### ISSUE THREAD

**Issue by nickbrisola** [Mytherin/Tibialyzer#134]
so, could we get a hud that gets a timer every time I cast utamo vita, or would this be considered cheating of some kind? :P thanks

**Comment by KuerbisGnu** [comment]
You can use the remindme command.
It is remindme@[time(in seconds)]@[Title]@[Message]@[Icon]
e. g. Magic Shield   remindme@200@Utamo vita@@Mana Shield

Put this command on hotkey and just remember to use both hotkeys every time you use mana shield.

**Comment by nickbrisola** [comment]
oh, nice. we can use the autohotkey as well:
-::SendMessage, 0xC, 0, "remindme@200@Utamo vita@@Mana Shield ",,Tibialyzer

**Comment by nickbrisola** [comment]
actually, I wonder if we could use the autohotkey as, in my case for the v letter:
v::F10+Command=remindme@200@Utamo vita@@Mana Shield 

or something like that, I'm not so good in programming, but if anyone knows how it should go, please help :D

**Comment by Mytherin** [comment]
See [my hotkeys](https://www.reddit.com/r/TibiaMMO/comments/4d7etk/getting_started_with_tibialyzer/d1oik5u) for how to do that.
```
8::
Send Ctrl+{F11}
Command=remindme@3m20s@Warning!@Magic Shield Expiring!@Magic Shield
return
```
