### ISSUE TITLE
Address updating

### ISSUE THREAD

**Issue by GalLuvton** [Mytherin/Tibialyzer#136]
I noticed that you have updated your addresses, even though the usual [source](https://github.com/blackdtools/Blackd-Safe-Cheats)(GitHub link) has yet to do so.
Would you mind sharing your methods? I tried to write some code to backtrack the tabs address, but I failed very hard...
I assume you have it automated, and learning from your methods would be great!

**Comment by Mytherin** [comment]
Everything is documented [here](https://github.com/Mytherin/Tibialyzer/wiki/Tibia-Updated,-What-Now%3F#how-do-i-update-the-addresses). I had actually forgotten how I did it so yesterday I just followed my own guide again. The only part that I have automated is the TabsBaseAddress; a link to the program is at the bottom. It's not a very sophisticated automation, as it assumes the internal structure of the tabs stays the same. The rest I found manually using the methods described there.

**Comment by GalLuvton** [comment]
I thought you automated the whole process (I do the exact same thing with anything that isn't tabs address). I guess I was hoping for some magic external or internal library that does what CE does for you (magically scanning the process' memory).
Nevertheless, your code for the tab address part will help a lot!
Thanks!

**Comment by Mytherin** [comment]
Not sure how to do that without botting in Tibia, because the way I use CE to find the addresses is to observe changing values, and you can't really change e.g. mana without casting a spell, so to do that automatically you would have to bot.
