### ISSUE TITLE
Tibialyzer didnt Start Windows 7 Professional

### ISSUE THREAD

**Issue by Slowmotion21** [Mytherin/Tibialyzer#138]
Hey there, 

I am trying to open Tibialyzer in another computer with Windows 7 and isnt opening. Dont give any menssage, just try to open and nothing happens. I already try to put in a not permission needed paste, and execute with admin permission, but doesnt work.

**Comment by Mytherin** [comment]
Did you install the .NET framework, as described in the “Installation Instructions” section?

**Comment by Slowmotion21** [comment]
I'll Check this, just missed that part, sorry.
