### ISSUE TITLE
translating into portuguese

### ISSUE THREAD

**Issue by nickbrisola** [Mytherin/Tibialyzer#141]
hello, again.
not an issue, but an offer. 
do you want me to translate the program into portuguese?
my guild members don't speak english so well, so I wanted to help them out without the need to teach each one of them.
if you are interested, chat me up! 
thanks again.
bye

**Comment by leosalvadori** [comment]
we have been discussing this, get up on  [#97](https://github.com/Mytherin/Tibialyzer/issues/97)

**Comment by nickbrisola** [comment]
oh. nevermind then :P
