### ISSUE TITLE
Tibialyzer is running but doing nothing

### ISSUE THREAD

**Issue by cinek1989** [Mytherin/Tibialyzer#143]
Hi there, I have problem with Tibialyzer; application is working (I have windows 7 professional), the green bar at the top left corner is running but that's all, any of the features of the program is not working. I've installed .net framework but it didn't help. I have checked in my options "show timestamples" and other options. Kindly advise what I can do to fix that. Note that few weeks ago in previous tibia version tibialyzer was working all fine.
Thanks!

**Comment by Mytherin** [comment]
Click the button 'Download New Addresses' on the Main tab.

**Comment by cinek1989** [comment]
You're awesome, thanks for such prompt replay!
