### ISSUE TITLE
Huds not working

### ISSUE THREAD

**Issue by larnfi** [Mytherin/Tibialyzer#144]
Hey, im new to tibialyzer.
i cant seem to get my healthbar huds working, it doesnt seem to read any char mana/hp or exp or anything. no huds is working for me.
is there anything i have t odo to make them work ?

**Comment by KuerbisGnu** [comment]
Hello,
check if your settings are correct. [Here](https://github.com/Mytherin/Tibialyzer/wiki/Settings-Guide#hud-tab)
And try to download new memory adresses.  [Here](https://cloud.githubusercontent.com/assets/17644820/17076198/adebc944-50ac-11e6-9541-4d72297c0d65.png)
