### ISSUE TITLE
Summary loot doesnt show items and creatures.

### ISSUE THREAD

**Issue by ruppy69** [Mytherin/Tibialyzer#147]
Hello Mytherin. As in topic. I download new addresses and new database but summary form still doesnt show dropped items and killed creatures. Popus works but summary not. How can i solve it ?

**Comment by Mytherin** [comment]
Try loot@ and then click the `All` button. If creatures or loot show up, you probably have either the `Ignore Low Experience` creatures set too high, or you have many items set to `No Pickup`.

**Comment by ruppy69** [comment]
Ok man. I have it now. Just realised it... Im noob...
