### ISSUE TITLE
thing about autohotkeys

### ISSUE THREAD

**Issue by krustzer** [Mytherin/Tibialyzer#150]
Hi, idk if this is a problem, so i resolved to post.

When Tibialyzer are maximized and i press my hotkey to "Suspend", the hud show on Tibiaclient and the autohotkey stop.

But if the tibialyzer are minimized in hidden icons and i press my "Suspend" hotkey, doesnt show the Suspended Hud on tibia client.

EDIT### - i found another thing, if tibialyzer are minimized on hidden icons, my hotkey of (summary@, reset@) when i press doesnt work too.

thxx

**Comment by Mytherin** [comment]
Minimizing to tray has been replaced with regular minimizing, so this should be "fixed" because minimizing to tray is no longer possible.
