### ISSUE TITLE
What is the command to change item value?

### ISSUE THREAD

**Issue by Vinibi** [Mytherin/Tibialyzer#151]
Hello guys,

I wonder what is the command to change the item value.
I was looking for it on Wiki, but I didnt find.

I know there are the arrows to change the value, but I want to remember the command to do that.

Thank you so much

**Comment by Mytherin** [comment]
`setval@itemname=value`

e.g.

`setval@mace=30` to set the value of Maces to 30.

**Comment by Vinibi** [comment]
Thank you very much Myt!
