### ISSUE TITLE
Search for teamhunt in tibialyzer

### ISSUE THREAD

**Issue by peternycander** [Mytherin/Tibialyzer#152]
I think we all can agree that Tibia could use a "looking for teamhunt"-function. Instead of waiting for CIP to implement it we could use the userbase of Tibialyzer to create our own. This will of course include programming a server and hosting it, etc. but with the amount of players in Tibia that could probably be done within the free tier of many hosting services.

In the Tibialyzer client we would have to create another tab, which integrates with the server. As a suggestion the server choice would be done via dropdown. Voc and level could be input manually.

**Comment by Mytherin** [comment]
It's a nice idea, but I think it's outside of the scope of Tibialyzer. It also requires a lot of effort and requires me to spend money on server infrastructure, so I'm going to pass on this idea.
