### ISSUE TITLE
Tibialyzer leaks process handles during memory scanning

### ISSUE THREAD

**Issue by Oddegamra** [Mytherin/Tibialyzer#156]
It is my understanding that Tibialyzer has an internal timer that periodically scans Tibia's memory using OpenProcess/ReadProcessMemory. Assumedly, the code was taken from [CodeProject](http://www.codeproject.com/Articles/716227/Csharp-How-to-Scan-a-Process-Memory), which usually isn't very good for serious programming due to severely lacking quality control. In any case, the process handle returned by [OpenProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684320(v=vs.85).aspx) should always be closed with [CloseHandle](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724211(v=vs.85).aspx) after the scanning is done to avoid leaking open process handles and depleting system memory.

**Comment by Mytherin** [comment]
Should be fixed in commit 3d5a492b04dd76ed6fac862329a71d6bb93bc4cf.
