### ISSUE TITLE
Settings get erased when computer shuts off unexpectedly.

### ISSUE THREAD

**Issue by bneedy** [Mytherin/Tibialyzer#157]
There have been a couple of times when my power has gone out or some other reason for my computer to get shut off unexpectedly.  When this happens the settings of my Tibialyzer gets reset somehow and I have to revert to a previous version.  Any changes I had made to this point are then erased.  Is there a way I can save a new settings once I change them again to another location so I can always fall back on that saved copy or prevent the settings from being erased when my computer gets shutoff.

**Comment by KuerbisGnu** [comment]
> Manual Updating:

> If the automatic updating does not work, you can manually update your settings by copying the _**Database\settings.txt**_ and **_Database\loot.db_** files from your previous Tibialyzer installation to your new Tibialyzer installation.

Just backup these two files. So you will always have your settings save. When you loose your settings again just replace these files and all are your settings are back.

**Comment by Sythius** [comment]
This just happened to me as well, not sure why.

**Comment by Mytherin** [comment]
This should be fixed by 67a021f043da7f93ef293969acebe62e920cfc49.
