### ISSUE TITLE
Problem in detect my character

### ISSUE THREAD

**Issue by DigaoHs** [Mytherin/Tibialyzer#158]
Hey,
tibialyzer open standard only does not recognize my character , is the configurations of their characters. What can it be? And i installed the net framework by 4.61 more not decided.

Look:
![image](https://cloud.githubusercontent.com/assets/6899008/17648403/49e3fa4e-61ea-11e6-9fe0-6f2880be7443.png)

**Comment by Mytherin** [comment]
Click the Download New Addresses button on the main tab.
![image](https://cloud.githubusercontent.com/assets/17644820/17455776/e0d1c63a-5bc2-11e6-9860-bf7f7eed71be.png)
