### ISSUE TITLE
Problem whit Autohotkey

### ISSUE THREAD

**Issue by Aliekh** [Mytherin/Tibialyzer#159]
Hi, my problem is i want to replace the control + f4 hotkey for control + V, but ist work.. any suggestion?

**Comment by Mytherin** [comment]
Try `Ctrl+V::Send {Ctrl+F4}`

**Comment by Aliekh** [comment]
it doesn´t work, can u screenshot all ur autohotkey? that could help me whit the problem, thanks and sorry for bad english

**Comment by Aliekh** [comment]
Oh it wooork! sorry i put Ctrl+V::Send {Ctrl+F4} instead of Ctrl+V::Send Ctrl+{F4},  your solution work! thanks alot man i love it
