### ISSUE TITLE
Screenshot for advanced skill while offline training shows login screen

### ISSUE THREAD

**Issue by Tschis** [Mytherin/Tibialyzer#160]
If you advance in skill while offline training, lyzer will actually screenshot the login screen instead of waiting for you to be logged in to screen shot it.

**Comment by Mytherin** [comment]
I can't really solve this issue, the logs are simply loaded into memory before the character finishes logging in. I don't really think anyone cares about "offline training" screenshots anyway, so I'm not planning on fixing this issue either.
