### ISSUE TITLE
Items can only be half looked

### ISSUE THREAD

**Issue by azmodian** [Mytherin/Tibialyzer#161]
Heya,

some items can only be half looked this means the half of the programm get's cut out.
Check pictures.

![tibia_2016-08-17_13-29-25](https://cloud.githubusercontent.com/assets/19708703/17734780/a5c6e092-647e-11e6-8043-173ea15b3c04.png)
![tibialyzer_2016-08-17_13-27-29](https://cloud.githubusercontent.com/assets/19708703/17734781/a5c92b90-647e-11e6-9588-a6351ad24722.png)

**Comment by Mytherin** [comment]
Should be fixed in the beta release.
