### ISSUE TITLE
TabStructure

### ISSUE THREAD

**Issue by Faceman8787** [Mytherin/Tibialyzer#166]
Hi there, 

does anyone of you know how the TabStructe is build? I have tried alot to find it out by myself but I dont get it right. I already found the address of chat name "Local Chat" and "Server Log", however I cannot read the lines of the chat. Any help woud be nice. 
I also tried to understand the written code of Tibialyzer but I did not help much much.
Thx.

Edit: I got it by now. If anyone else is intersted in knowing, just send me a msg :)
Thx anyway.

**Comment by klief1** [comment]
@Faceman8787 how did u do it? did u do it on tibia 11?

**Comment by Faceman8787** [comment]
I looked up the file Tibialyzer/blob/master/Tibialyzer/Managers/MemoryReader.cs and read the code. Before the update there was a method which was reading thourgh the tabs. Now I just had a quick look over it and could not find it. 
So no, I did not do it on tibia 11. Currently out of prem and time, thus I doubt I will do it in the next time.
