### ISSUE TITLE
[Suggestion] Checkbox for healthlist members

### ISSUE THREAD

**Issue by Tschis** [Mytherin/Tibialyzer#168]
If you have many friends you want to keep track at different times, you have to keep adding and removing them from the health list, otherwise, sometimes their HP is show there outdated and just takes up space, even if they're offline.

How about a checkbox besides each name, so that only the ones that are checked will show?
It will make management of those names easier, you won't have to keep deleting/adding them every time.

**Comment by Mytherin** [comment]
This should be made obsolete by 55e0473e964f5e76c506e597df0aee487f377ac0.
