### ISSUE TITLE
Tibia 11 and Tibialyzer 1.4.0-beta 

### ISSUE THREAD

**Issue by Shoax** [Mytherin/Tibialyzer#169]
Hello, I've got a problem using Tibia 11 and the newest tibialyzer. So the problem is that it works for awhile(usually 5-10 mins) and then the scanning bar turns gray and tibialyzer stops scanning. I tried it with Tibia 10 and worked properly.

**Comment by kubax36** [comment]
I've same problem, it seems to stops randomly, sometimes it works 5min, sometimes even 1h. It will stop to scan sooner or later anyway.

**Comment by Mytherin** [comment]
This was actually already fixed in 3a683fee6d14271fe6d3777f6d4674d0a7fd22cf; I updated the release to include this fix now. You can find the new release [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.4.1-beta).
