### ISSUE TITLE
After the Upload on 08/30/2016 Tibializer has stoped working 

### ISSUE THREAD

**Issue by Emsanga** [Mytherin/Tibialyzer#172]
Need Help to solve this Issue Mytherin ....

**Comment by Emsanga** [comment]
After de Update""

**Comment by azmodian** [comment]
Wait for an Update. Adresses needs to be changed.

**Comment by insectx89** [comment]
for me works fine...

**Comment by Mytherin** [comment]
The addresses are updated. To update click the Download New Addresses button on the main tab.
![image](https://cloud.githubusercontent.com/assets/17644820/17455776/e0d1c63a-5bc2-11e6-9860-bf7f7eed71be.png)
