### ISSUE TITLE
Tibialyzer Randomly Resets

### ISSUE THREAD

**Issue by CainCapone** [Mytherin/Tibialyzer#174]
Hello Mytherin, i love your program i really do, i think its awesome that you give us tibialyzer for free, but bro i can't use it and neither can my friend.....we spend hours customizing our tibialyzers to our liking and in 30 minutes or maybe even 3 days the program will randomly reset as if we have just downloaded it......and can not restore our settings because the folder we extracted to desktop also has somehow reset when looking at the database it shows nothing has been modified....i'm extracting the archive to desktop....please help because i want to use tibialyzer but i just can't like this.....EDIT: could i just keep a backup copy of my database settings notepad file? because when this bug happens my notepad settings file also acts as if its brand new again...but if i save a backup copy named as tibialyzer settings backup for example could i just open my database settings file and open my backup and copy/paste swap the 2??? let me know cause im willing to do this if it works.

**Comment by Mytherin** [comment]
Try the [beta release](https://github.com/Mytherin/Tibialyzer/releases/tag/1.4.1-beta), this should have fixed the Settings corruption issue. 

You can just backup the entire "Database" folder, if you want to make a backup. Then replace the "Database" folder with your backup if something happens. Even easier would be to copy the entire Tibialyzer folder with your settings.

**Comment by CainCapone** [comment]
thanks alot bro i got tibialyzer setup 100% how i like it and made a backup :)
