### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by Nenkirl** [Mytherin/Tibialyzer#177]
Hi,
i am just wondering, can i bind Control +1 in tibialyzer? when i binded with <^ etc the bind Control+F1 came up. I really want like flash client, binds like ctrl 1-5 Alt 1-5 and Shift 1-5.

Best Regards Joakim﻿

**Comment by KuerbisGnu** [comment]
Hello,
try this
Ctrl+1::Send {F1}
Alt+1::Send Ctrl+{F1}

It should work.

**Comment by Nenkirl** [comment]
thanks and with shift its the same? like Shift+1::Send Ctrl+{F1}?

**Comment by Nenkirl** [comment]
i have also a important question. i have on flashclient a important bind which is Ctrl+F but on old client its full screen is there anyway u can go around it and like unbind fullscreen etc?

**Comment by Nenkirl** [comment]
Thanks for the Help man!. just 1 more question, do u know how to bind to turn? turn N,S,E,W what the command is in flash u use Shift+W,A,S,D

**Comment by Nenkirl** [comment]
Hi,

Does anyone knows how i can rebind Turns from Ctrl+W,A,S,D to Shift keys instead.

Best Regards Joakim
