### ISSUE TITLE
Hotkeys Turning

### ISSUE THREAD

**Issue by Nenkirl** [Mytherin/Tibialyzer#178]
Hi,

Does anyone knows how i can rebind Turns from Ctrl+W,A,S,D to Shift keys instead.

And in where or with what command

Best Regards Joakim

**Comment by KuerbisGnu** [comment]
Hello,
it is just the same as with your other hotkeys.
Ctrl+W::Send Ctrl+{Up}
Ctrl+S::Send Ctrl+{Down}
Ctrl+A::Send Ctrl+{Left}
Ctrl+D::Send Ctrl+{Right}

**Comment by Mytherin** [comment]
See [here](https://github.com/Mytherin/Tibialyzer/issues/25).
