### ISSUE TITLE
[Question] Is there any way to save the settings?

### ISSUE THREAD

**Issue by lordzim** [Mytherin/Tibialyzer#180]
Sometimes, my pc random reboot, and when i open tibialyzer all my configs are lost. I don't know why.
There is someway to backup my configs?

Thanks for any kind answer

**Comment by Mytherin** [comment]
Try the [beta release](https://github.com/Mytherin/Tibialyzer/releases/tag/1.4.1-beta), this should have fixed the Settings corruption issue. 

As for backing up settings, you can backup the entire "Database" folder, if you want to make a backup. Then replace the "Database" folder with your backup if something happens. Even easier would be to copy the entire Tibialyzer folder with your settings.

**Comment by lordzim** [comment]
Yes! Thanks, i backup setting.txt. I think it will work. Thanks Mytherin!
