### ISSUE TITLE
Running Tibialyzer on OTserv 10.93

### ISSUE THREAD

**Issue by kito2** [Mytherin/Tibialyzer#182]
Hello,

The health curved bars are not working, and the entire Tibialyzer isn't wokring.

Alreayd tried to download new addresses but nothing.

Cliente 10.93

**Comment by Mytherin** [comment]
You need the addresses for version 10.93. Write this to your MemoryAddresses.txt file.

﻿XORAddress=0x5376A0
HealthAddress=0x6D5000
MaxHealthAddress=0x6D502C
ManaAddress=0x5376D0
MaxManaAddress=0x5376A4
LevelAddress=0x5376B8
AmmunitionCountAddress=0x775774
AmmunitionTypeAddress=0x775778
WeaponCountAddress=0x7757F4
WeaponTypeAddress=0x7757F8
ExperienceAddress=0x5376A8
PlayerIDAddress=0x6D5034
BattleListAddress=0x72F6F0
TabsBaseAddress=0x53796C
```

**Comment by kito2** [comment]
Not working.

Replaced everything on the MemoryAddresses.txt with your info and nothing.

Could you add an option to download specific memory addresses, so this could work on OTs too?

Thanks.

**Comment by Mytherin** [comment]
Added, try [downloading the new beta.](https://github.com/Mytherin/Tibialyzer/releases/tag/1.4.2-beta).

**Comment by kito2** [comment]
Thanks, it is working right now and the beta seems to be pretty friendly.
