### ISSUE TITLE
No tibia client found....

### ISSUE THREAD

**Issue by fenio987** [Mytherin/Tibialyzer#183]
Hello.
It's been week since tibialyzer worked for me,for some reason it cannot find my tibia client.
And this database error http://i.imgur.com/XqRkl8C.png

**Comment by Mytherin** [comment]
Try downloading [the beta](https://github.com/Mytherin/Tibialyzer/releases/tag/1.4.1-beta) and see if it fixes your issue. Otherwise, take a screenshot of the ENTIRE error message. I cannot help you with the image you have provided.

**Comment by fenio987** [comment]
No tibia client found.
http://i.imgur.com/OrIZ07Y.png
Same thing in the beta version
http://i.imgur.com/myTkoMT.png
That was the entire error:Database scan error (non-fatal):access denied

**Comment by Mytherin** [comment]
Try launching Tibialyzer as administrator, or putting the "Tibialyzer" folder on your Desktop or in your Users folder.

**Comment by fenio987** [comment]
That helped!Thank you very much.
