### ISSUE TITLE
[Suggestion] Multi-monitor support for notifications

### ISSUE THREAD

**Issue by cosmicflame** [Mytherin/Tibialyzer#187]
Hi,

Firstly, I am *loving* Tibialyzer!

A suggestion:

It would be really good if individual notification types could be anchored to a specific monitor, rather than all notifications being anchored on the same monitor.  This would allow users to separate out small, inline displays that don't cover the play area from larger ones that do.

E.g:

On Tibia Client monitor:
- Loot notification (small popup)
- Summary form (small, thin form)

On Tibialyzer Monitor:
- Damage Notification (large pie chart)
- Object List (fairly wide table)

I'm not a C# developer, but I've got some .Net experience so I'd be happy to have a hack at implementing this at some point, if you don't feel that it belongs that high up the backlog.

Thanks,

Cosmic Flame, Secura

**Comment by Mytherin** [comment]
You can already accomplish this by simply setting the "X Offset" to a large value (or negative, depending on where your monitors are in relation to one another). Don't really see a need for this unless you frequently change your monitor setup, although it should be relatively simple to implement.

**Comment by cosmicflame** [comment]
Ah yes, I see your point...  It feels like a clunky way of setting it up, but as it's a one-time job that's fine.  Workaround exists, closing ticket.

(and thanks for the quick response! :) )
