### ISSUE TITLE
Not counting platinum coins

### ISSUE THREAD

**Issue by Galarzaa90** [Mytherin/Tibialyzer#19]
I have my Tibialyzer set to not consider gold coins (selected gold coins and unchecked "Pick Up Item"), but I have platinum coins checked, because I only pick up platinum coins when hunting.

The problem is that Tibialyzer is not considering the platinum coins I pick. If I uncheck and check platinum coins, the total value doesn't change at all. If I check gold coins, then it considers all money.

**Comment by Mytherin** [comment]
This issue should already have been [resolved](https://github.com/Mytherin/Tibialyzer/issues/8), are you using the latest release?

**Comment by Galarzaa90** [comment]
Hmmm, feature request right there, an about section to check the current version :)

As far as I know, I have v1.1, the first update you released when you announced CipSoft tolerates your program now, with the UI overhaul, stack all items, better notification customization, etc, the one you posted on reddit.

Here's a hunt I've saved, at Oramond:
![image](https://cloud.githubusercontent.com/assets/12865379/13445258/60f649fc-dfc8-11e5-8ef0-15494937e380.png)
That's the "Normal" view with platinum coins selected, and gold coins unchecked.

![image](https://cloud.githubusercontent.com/assets/12865379/13445276/7ad667bc-dfc8-11e5-8f06-84abc207fcd4.png)
This is the "All" view, with the same settings

----
![image](https://cloud.githubusercontent.com/assets/12865379/13445332/c5e303c8-dfc8-11e5-9e34-e8b276af2019.png)
Same hunt, "Normal" view, now platinum and gold coins unchecked, notice how the gold value didn't change

![image](https://cloud.githubusercontent.com/assets/12865379/13445351/e0c1d07a-dfc8-11e5-8e8e-c1e6c304e09a.png)
"All" view, remains the same

-----

![image](https://cloud.githubusercontent.com/assets/12865379/13445402/18fc9bbe-dfc9-11e5-91fc-266689a762a8.png)
"Normal" view, gold coins checked, platinum coins checked (unchecking platinum coins makes no difference)

**Comment by Mytherin** [comment]
I didn't make a new release for this fix, I simply updated the 1.1 release because it was such a minor fix. I think you still have the old version. Try downloading the latest release again, that should fix the issue.

**Comment by Galarzaa90** [comment]
That fixed it, thank you! Sorry about that :)

**Comment by Mytherin** [comment]
Alright, I will close this issue.
