### ISSUE TITLE
Tibialyzer stopped working on Tibia 10 after testing it on Tibia 11

### ISSUE THREAD

**Issue by rankored** [Mytherin/Tibialyzer#191]
I was testing the new client and it was running like shit, the performance is awful.

Now I wanted to play on Tibia 10 again, and it's not working :< it hooks correctly, the bar at top left is green, is just doesnt count loot or reacts to ingame commands. I even reinstalled both tibia and tibialyzer, still not working :(

Im using 1.4.2

**Comment by Mytherin** [comment]
This is because of the Tibia 10 update; the memory addresses should be updated now.

**Comment by rankored** [comment]
Oh wow, I panicked because of coincidence, thanks for answering.
