### ISSUE TITLE
Own drop rate database

### ISSUE THREAD

**Issue by Gromah** [Mytherin/Tibialyzer#194]
I was wondering if it's possible by you to create a feature to store all collected loot and then browse it? Maybe would it be possible to send it to the server(?) and you would be able to create tibialyzer users drop rate statistics (i guess tibialyzer uses stats from tibia-wikia right now)?

**Comment by Mytherin** [comment]
I have thought about collecting statistics, but I really don't want to go through the trouble of doing so. It would definitely be possible but it's not on my list of plans. Thanks for the suggestion, though.
