### ISSUE TITLE
Don’t copy the entire Tibia memory

### ISSUE THREAD

**Issue by mathiasbynens** [Mytherin/Tibialyzer#2]
<https://www.reddit.com/r/TibiaMMO/comments/43k89u/introducing_tibialyzer_a_realtime_tibia_analyzer/cziwam6>:

> Are you really copying the entire memory of Tibia and searching it for strings matching a pattern? You realise it would be 1000x more efficient to find the data structure of the GUI which displays them and use that? You'd have to read max a few KB and it would all be information which you actually need...

**Comment by Mytherin** [comment]
Already fixed, see [this commit](https://github.com/Mytherin/Tibialyzer/commit/0489a35ef3db10d7844c68eec5bdefc0ecbc64a3).

**Comment by mathiasbynens** [comment]
:+1: Perhaps you could tag a new release, then? I noticed some people were [complaining](http://forum.tibia.com/forum/?action=thread&threadid=4442271&postid=37377863#post37377863) of Tibialyzer being overly resource-intensive — this patch of yours would surely help with that!

P.S. Have you considered using [the semver versioning scheme](http://semver.org/)? Since the initial release was 1.0.0, this would make the new release 1.1.0.

**Comment by Mytherin** [comment]
I will publish a new release on Saturday, I still have some changes I want to make before publishing the new release.
