### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by XtrmJosh** [Mytherin/Tibialyzer#217]
Hi Mytherin,

We've spoken before. I need to contact you but can't remember your reddit username. Could you please drop me a message either on Reddit (XtrmJosh - https://www.reddit.com/user/XtrmJosh/) or some other means. You can find me in many places. I have some information which may be beneficial to this project (and might be willing to help you move it forward for the new client).

Sorry to raise a bug for this, but I genuinely can't think of any other way (short of messaging you ingame, and I cba to make a new character and do all that) to contact you. For reasons you'll understand later I cannot discuss this openly. What I'm offering is effectively free, hopefully very useful information which might help you to update.

Regards

**Comment by Mytherin** [comment]
I remember you, and your previous information helped me a lot. My reddit username is /u/BadgerBadger8264, but you can also email me at mark.raasveldt [at] gmail.com.
