### ISSUE TITLE
Tibialyzer can't detect my client

### ISSUE THREAD

**Issue by Broda922** [Mytherin/Tibialyzer#219]
Hey,

I just downloaded Tibialyzer (it's on my desktop and I run it as administrator), typed in the names of my characters, downloaded new adresses but it seems like it doesn't "connect" to my client. When I type a command ingame (like creature@demon) nothing happens or if I have the summary window opened and I kill a random creature, it doesn't count the exp or the loot. I already used the "select tibia client" option, but even if I select the windows process/task of my Tibia 11, it still ain't working. 

Am I missing something? Thanks in advance for your help.

**Comment by Mytherin** [comment]
Download version 1.4.2, you downloaded an old version.

**Comment by Broda922** [comment]
Oh thanks a lot, didn't know I downloaded an old version.
