### ISSUE TITLE
Doesn't work on full screen.

### ISSUE THREAD

**Issue by Fmancio** [Mytherin/Tibialyzer#22]
When tibia is in fullscreen mode, tibialyzer dont show any of it's informations. There is a way to solve this?

**Comment by villor** [comment]
This might be hard without hooking the process and drawing the overlay using DirectX or something like that. This would mean actual manipulation of the process, which is probably against the rules.

**Comment by Mytherin** [comment]
There is no legal way to solve this. When you play in fullscreen mode, you are giving Tibia exclusive access to that monitor, meaning no other windows can render on that screen. The only way to then render onto that screen is to render onto the Tibia Client window directly, which is against the rules as you would be directly altering the Tibia client.

**Comment by Mytherin** [comment]
I'm closing this because I don't see any possible way of solving this issue without violating the Tibia rules. If anyone has any suggestions on how this could be done, you can reopen this issue.
