### ISSUE TITLE
Possible fake Tibialyzer website?

### ISSUE THREAD

**Issue by benjaminkomen** [Mytherin/Tibialyzer#224]
Somebody made an account User:Mytherins on TibiaWiki and changed some links from this github project to the following website: www.tibialyzer.eu. This seems fishy to me, since the website is registered in Poland. Is this website yours, Mytherin, or is it trying to hack people?

**Comment by mathiasbynens** [comment]
Definitely fishy. The download link points to a file on Google Drive instead of to the downloads of this project, and the Facebook link at the bottom leads to `https://www.facebook.com/anthraxbot`.

**Comment by mathiasbynens** [comment]
Perhaps a warning like this could be added to the top of the README:

> **Warning:** The only official Tibialyzer website is `https://github.com/Mytherin/Tibialyzer`. “Hackers” are creating fake websites containing malicious downloads (possibly containing viruses or keyloggers) instead of the real Tibialyzer. **Only download Tibialyzer through this webpage!**

**Comment by Mytherin** [comment]
I added a warning to the top of the page (133c626af8a1a55d32628d43c86963f67d7a9d57).

**Comment by benjaminkomen** [comment]
Ok, thanks for taking care of it. I guess this hack attempt means your program is getting some widespread attention in the Tibian community.
