### ISSUE TITLE
Tibialyzer not working on Client 10.97

### ISSUE THREAD

**Issue by kito2** [Mytherin/Tibialyzer#226]
Hey does this just works on Tibia 10.98 and Client 11?

Would be wonderfull to make it works on different clients.

**Comment by Mytherin** [comment]
Go to `Settings -> Advanced` and select the memory addresses for Tibia 10.97, then click Download Addresses.

**Comment by kito2** [comment]
Thanks!

**Comment by WIMdowz** [comment]
cool thx
