### ISSUE TITLE
Tibialyzer not working

### ISSUE THREAD

**Issue by Perezinho** [Mytherin/Tibialyzer#228]
Did anyone have the same error as myself ?
After I downloaded Tibialyzer and run (.exe) Application nothing happens. Not even a single error pop-up window. Absolutely nothing so I can't even diagnose the problem why it's not working.

**Comment by Mytherin** [comment]
Did you install the .NET framework as specified in the [Installation Instructions](https://github.com/Mytherin/Tibialyzer/wiki/Installation-Instructions)?

**Comment by Perezinho** [comment]
I was sure I had it, but it was previous versions of it :P Thanks
