### ISSUE TITLE
Damage analyzer includes creature's damage.

### ISSUE THREAD

**Issue by kugrjado** [Mytherin/Tibialyzer#24]
When I hunted Sea Serpents I noticed that some of their damage is included in damage statistics.
<img src="http://i.imgur.com/OyKBwkT.jpg"/>

**Comment by Mytherin** [comment]
Interesting, I think this is related to Sea Serpents in particular. Thanks for reporting this issue, I will look into it.

**Comment by Mytherin** [comment]
Should be fixed with commit ad6bf3630b13d802084f9ccd120fcbd947110f1a.
