### ISSUE TITLE
Adjust Size of Summary Form

### ISSUE THREAD

**Issue by MercenaryRocky** [Mytherin/Tibialyzer#248]
Hello, I would like to know how to adjust the max length that this display box can go. I only want it to be displayed down to where the cool down icons are. I've been looking around & can't seem to fix this issue. Any help is appreciated, thanks!

![make this smaller](https://cloud.githubusercontent.com/assets/24354130/20859130/f795fa9e-b923-11e6-99ac-9335ea15acfa.png)

**Comment by Mytherin** [comment]
Look at the [Summary Tab](https://github.com/Mytherin/Tibialyzer/wiki/Settings-Guide#summary-tab), you can limit (or remove) different components of the summary form.

**Comment by MercenaryRocky** [comment]
You sir & creator are thanked very much. I'm just beginning to use your tool & so far I love it. I hope you have a great day or night.
