### ISSUE TITLE
Turning Character Using WASD

### ISSUE THREAD

**Issue by Sythius** [Mytherin/Tibialyzer#25]
Does anyone have a suggestion for having Shift be the key modifier for turning when using WASD?

I had a great idea of making auto hotkey changes to make Shift+W = Ctrl+Up for example, however the issue is that it does not differentiate between the normal WASD hotkey and this one.

If I do Shift+W = Ctrl+Up, and then use Shift+W, it does Shift+Up as it would normally do, making it so that the previous chat message appears.

I want to make it so that normal WASD does Up Left Down Right, but that Shift+WASD does Ctrl+Up Left Down Right, not Shift+Up Left Down Right.

Any thoughts on creating a separation between the modifiers?

The reason I want to change to Shift+WASD is due to being used to the flash client settings, and the ergonomics of it are much more comfortable.

I don't know if this change may cause other potential issues, but without being able to test it, I won't be able to know at all.

Thoughts?

**Comment by Mytherin** [comment]
This isn't really a Tibialyzer issue as much as it is an AutoHotkey issue. But I looked into it for you, and this seems to work for me.

```
Shift+W::Send Ctrl+{Up}
Shift+A::Send Ctrl+{Left}
Shift+S::Send Ctrl+{Down}
Shift+D::Send Ctrl+{Right}
```

**Comment by Sythius** [comment]
Amazing! Thanks Mytherin! It works wonderfully!
