### ISSUE TITLE
no exe program

### ISSUE THREAD

**Issue by Diogomnunes** [Mytherin/Tibialyzer#265]
i did download the tibialyzer but it does not have the tibialyzer.exe so i can  use it

**Comment by Mytherin** [comment]
You downloaded the source code, the executable can be found [here](https://github.com/Mytherin/Tibialyzer/releases/download/1.4.3.2-beta/Tibialyzer.1.4.3.2-beta.zip).

**Comment by Diogomnunes** [comment]
thanks
