### ISSUE TITLE
Loot Popup and counting don't work correctly on Fury

### ISSUE THREAD

**Issue by KuerbisGnu** [Mytherin/Tibialyzer#29]
I missed some Terra rods and steel boots popups on Fury hunt. Sometimes it works but not to 100%. 
The missed popup items are not shown in the loot@ notification.
I also killed alot of Spectre in the same hunt and on Spectre it works all good and i don't miss a single item.

My scanning speed is set to "Fast (35)".

I just wondering because I only see this issue on Furys.

Is it possible at all that there is an issue on a single monster?

**Comment by Mytherin** [comment]
The reason for this is that Furies drop Jalapeño peppers; and Tibialyzer currently does not handle Unicode characters correctly. Hence, any Fury that drops a Jalapeño pepper is ignored.

**Comment by Mytherin** [comment]
Should be fixed by c078f00501bc5041393dfb09b1104a8fa0461dfe. I've updated the release [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.2.0-beta).

**Comment by KuerbisGnu** [comment]
I made some tests. Works good. 
Thank you!
Can be closed.
