### ISSUE TITLE
Tibialyzer on 8.0

### ISSUE THREAD

**Issue by Kalindro** [Mytherin/Tibialyzer#299]
Hello! The Tibialyzer doesen't seem to work with Tibia 8.0? Am I retarded or there is no compatible Tibialyzer with 8.0?

**Comment by Mytherin** [comment]
Tibialyzer is only compatible with Tibia versions for which it has memory addresses; it also only works on Tibia versions that have the server log available. You can change the Tibia version in the `Advanced -> Old Memory Addresses` section. However, it seems 8.0 is indeed not available there. If it has a server log, you can try to figure out the addresses yourself using the method described here: https://github.com/Mytherin/Tibialyzer/wiki/Tibia-Updated,-What-Now%3F#how-do-i-update-the-addresses
