### ISSUE TITLE
Is there a chance for Tibialyzer working after Battleye integration?

### ISSUE THREAD

**Issue by SantosAdan** [Mytherin/Tibialyzer#325]
Hello @Mytherin, I'd like to know if you have any news about the status of Tibialyzer now that Battleye doesn't allow it to run.

Since it doesn't violate any Tibia rules and is a great tool, it'd be fantastic if you could provide us any feedback about it's either a dead tool or it'll shine again soon.

Thanks!

**Comment by MyMindisfree** [comment]
SantosAdan

"TibiaLyzer features to become part of Tibia 11 this summer

"Dear Tibians!
We have some news for you about Tibialyzer in regards to the integration of BattlEye.
As mentioned in one of my previous replies, the popularity of Tibialyzer did not go unnoticed by us. Infact, we think that Tibialyzer offers pretty cool features that make a nice addition to the game. However, as a side-effect of BattlEye, Tibialyzer will no longer work once Battleye has been integrated into our clients. We understand, of course, that fans of Tibialyzer would surely miss it dearly. However, whitelisting certain tools and applications that are actually blocked by BattlEye involves a risk that we do not want to take at the moment. Other work-arounds for such tools that would require adjustments on our side may also lead to potential problems and unwanted side-effects
At the same time, there are players who would who like to see an official feature similar to Tibialyzer but without the need to download additional, unauthorised software. So inspired by Tibialyzer, we are planning to develop and implement parts of it as an official feature in Tibia 11 to further enrich your gameplay experience. Please understand that we cannot yet provide a reliable timeframe but we're aiming for releasing it as a part of the summer update.
Mytherin, the developer of Tibialyzer, has already been informed about this yesterday and we also received a reply from him so he's aware of our plans.
Yours, Mirade"
Source: http://forum.tibia.com/forum/?action=thread&threadid=4532071&pageitems=20&pagenumber=23

:)

**Comment by SantosAdan** [comment]
Thanks @MyMindisfree, they released a note about this new features being released on 2017 summer update! Let's hope it gets to the community asap.

**Comment by gabrielbuzziv** [comment]
You can use if the server don't require BE.
Just open the %appdata% and find the 2 launcher files of tibia. the client.exe one work with tibialyzer 1.4.3
