### ISSUE TITLE
Tibialyzer 1.4.3.2 is not working (Tibia 10)

### ISSUE THREAD

**Issue by Mobaius** [Mytherin/Tibialyzer#334]
Hey.

Downloaded Tibialyzer for the first time and it seems like its not working for me.
I think the Tibialyzer can't find the tibia client but im not sure. there is a red line
instead of green (i saw on youtube it suposse to be green).

I tried "Select Tibia Process" but then i had a yellow-triangle at the top-left corner and nothing happend.

I tried this page: https://github.com/Mytherin/Tibialyzer/wiki/Issues
but nothing helpped me.

Any help? :/

**Comment by Mobaius** [comment]
It seems to find the Tibia 11 client but even if it finds it the tibialyzer is not working.
Only huds are working and they are not updating so its not so helpful...

**Comment by gabrielbuzziv** [comment]
@Affergan43 https://www.reddit.com/r/TibiaMMO/comments/6dha6y/tibialyzer_in_tibia_11_with_be_analzing/

This is how you can make this work in tibia 11

**Comment by Mobaius** [comment]
@gabrielbuzziv 
Thanks a lot. works :P
