### ISSUE TITLE
memory addresses for tibia 10.100 client

### ISSUE THREAD

**Issue by alexkohjc** [Mytherin/Tibialyzer#337]
hey guys im playing an OT (not sure if u guys frown about this but... yeah) and im using a 10.100 client. however, my health HUDs, party HUDs, etc. aren't working as I do not have the addresses for 10.100 and it looks a lil complicated to get it. so just trying my luck here to see if anyone has those values.

thanks!

**Comment by marcosvpb** [comment]
try this
PlayerIDAddress=0x70F050
BattleListAddress=0x76A48C
HealthAddress=0x70E000
MaxManaAddress=0x57045C
ManaAddress=0x57048C
TabsBaseAddress=0x570744
XORAddress=0x570458
MaxHealthAddress=0x70E048
AmmunitionCountAddress=0x7B147C
AmmunitionTypeAddress=0x7B1480
WeaponCountAddress=0x7B14FC
WeaponTypeAddress=0x7B1500
LevelAddress=0x570470
ExperienceAddress=0x570460
ClassicClientName=Tibia
Tibia11Name=client
Tibia11XPos=Qt5Core.dll + 004555C8 > 8 > 134 > 24 > 18
Tibia11YPos=Qt5Core.dll + 004555C8 > 8 > 134 > 24 > 1C
Tibia11ZPos=Qt5Core.dll + 004555C8 > 8 > 134 > 24 > 20
Tibia11MyHP=[2] Qt5Core.dll + 004555C8 > 8 > 124 > 60 > 18
Tibia11MyMaxHP=[2] Qt5Core.dll + 004555C8 > 8 > 124 > 60 > 1A
Tibia11Experience=[8] Qt5Core.dll + 004555C8 > 8 > 124 > 60 > 28
Tibia11Level=[2] Qt5Core.dll + 004555C8 > 8 > 124 > 60 > 30
Tibia11MyMana=[2] Qt5Core.dll + 004555C8 > 8 > 124 > 60 > 60
Tibia11MyMaxMana=[2] Qt5Core.dll + 004555C8 > 8 > 124 > 60 > 62

**Comment by michaeljankowski772** [comment]
Addresses posted by marcosvpb are working perfectly on the newest update of real tibia 11 by 08.06.2017. Thank you very much for contribution, it made my tibialyzer work!

**Comment by alexkohjc** [comment]
holy crap marco. this worked. thanks a LOT i've tried many ways almost resorting to figuring out how cheat engine works but..... i installed it and it installed some... programs on my computer (i didnt see any option to not install them. urgh) 

thanks once again
