### ISSUE TITLE
adding delay to ALL hotkeys

### ISSUE THREAD

**Issue by alexkohjc** [Mytherin/Tibialyzer#338]
hey guys,

im back with another issue lol.

so im playing an EK and what i do is to hold down my MP pot hotkey and my exura ico hotkey, or MP and exori/exori gran keys...... so what happens is that i'll get kicked from the server, presumably from holding down too many hotkeys. whenever im holding down my hotkeys, there will be a lot of "smoke" on my character, which doesn't seem to happen when i was using the standard F keys.

As such, is there any command that will allow me to perhaps add 0.1-0.5 seconds of delay to all my hotkeys? or is there any other way to resolve this?

thanks!

**Comment by marcosvpb** [comment]
Change the interval key press down on Windows.
Win Button -> Keyboard -> Repeat Interval/Repetition Rate.
maybe it works.
