### ISSUE TITLE
Jalapeño Pepper Popup Issue

### ISSUE THREAD

**Issue by Sythius** [Mytherin/Tibialyzer#35]
As it turns out, if a creature drops any amount of Jalapeño Peppers, it prevents a popup from occurring. This creates a scenario where a Fury may drop Golden legs and a couple of Jalapeño Peppers, but the player has no idea, because there is no popup. I would imagine that it has something to do with the ñ in Jalapeño Pepper. 

I have not personally tested this, but a friend of mine was hunting Fury Gate and had this issue repeatedly.

**Comment by Mytherin** [comment]
This should already be fixed, see Issue #29. Try downloading the latest Beta release [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.2.0-beta).

**Comment by Sythius** [comment]
I will let him know and have him test it again. Once he verifies i will close the issue.

Thanks Myth.

**Comment by Sythius** [comment]
Okay he tested it very quickly. It looks like everything is in order. Thanks. Closing the issue now.
