### ISSUE TITLE
compilation issues

### ISSUE THREAD

**Issue by GalLuvton** [Mytherin/Tibialyzer#40]
![image](https://cloud.githubusercontent.com/assets/7879574/14085210/44a272ca-f527-11e5-920c-7c453cad3cce.png)
I have been having some compilation issues for quite a while now.
They keep stacking up, and they all seem quite logical.

Do you compile with any flags on that I should know of? I get this error on several instances of VS2015 (2 different PCs)

**Comment by GalLuvton** [comment]
The lines numbers are for commit ec4d387fc817ed22a64d42179877f912bc075624

**Comment by Mytherin** [comment]
Interesting, I use pretty much the default settings of VS2015 everywhere. I haven't changed much. Not sure what would cause this.

**Comment by GalLuvton** [comment]
Closing, seeing how no one else complains about this, and I have a workaround anyways for my local compilation.
