### ISSUE TITLE
HUB for Loot

### ISSUE THREAD

**Issue by engelsoto** [Mytherin/Tibialyzer#43]
HIIIIII
thanks for this excellent tool, today discovered and  not stop surprise of many options

I think that would be an excellent Loot HUB same window only to permanent

thanks for the excellent contribution and maybe soon i can see this option :)))

**Comment by GalLuvton** [comment]
This isn't an optimal solution, but for now, you can:
1. Go to notifications
2. Find the loot notification
3. Set the duration to 'Infinite'

This would make sure the loot window never closes. Its close to what you asked for, but whenever you will open a new notification (waste, damage charts, etc.), it will replace the loot notification, and you would have to open it again.
This would work for now as a temporary solution.

**Comment by Mytherin** [comment]
The rule for notifications is that you can have one notification open per display group. By default, all notifications are in Display Group 1, meaning you can only have one notification open at a time.

However, if you place the Loot Notification in Display Group 2, the notifications in Display Group 1 will not close the Loot Notification, thus allowing you to open other notifications (such as waste or damage chart) without closing the loot notification.

**Comment by kugrjado** [comment]
@Mytherin Oooh, so this is how these groups work! It explains a lot now.

**Comment by GalLuvton** [comment]
@engelsoto Please close this issue since it has been addressed
