### ISSUE TITLE
Rune in the mouse pointer

### ISSUE THREAD

**Issue by sossoh555** [Mytherin/Tibialyzer#44]
First, one more time, congratulations for this amazing program! (: :+1: 

Second, a suggestion: what about when you select a rune and it shows at right bottom of the mouse pointer like a small icon?
It would work as the HUB but it would follow the mouse pointer and when selected you would know what rune or whatever you are using to.

Is this the best place to suggestion? :o

Thank you.
Regards,

**Comment by GalLuvton** [comment]
@sossoh555  Please post it on issue #39 'Todo List'. That was supposed to be the 'suggestion' issue.
