### ISSUE TITLE
Looking at "books of necromantic rituals."

### ISSUE THREAD

**Issue by bneedy** [Mytherin/Tibialyzer#45]
When looking at a stack of books of necromantic rituals, I get this message:

20:04 You see 16 books of necromantic rituals.
They weigh 57.28 oz.

Which will not bring up the information about where to sell, etc.

This is probably part of the plural version of this item, because when looking at a single item of this I see the message:

20:05 You see a book of necromantic rituals.
It weighs 3.58 oz.

Which does correctly bring up the item's information.

**Comment by Mytherin** [comment]
Thanks for the bug report; should be fixed with commit cf0e5cace0b642381a0f7d80b133f06c5ec53732.
