### ISSUE TITLE
Visual Studio "Express" is now Visual Studio "Community Edition"

### ISSUE THREAD

**Issue by XtrmJosh** [Mytherin/Tibialyzer#48]
As per title, link in README.md needs updating.

New link:

https://www.visualstudio.com/products/visual-studio-community-vs

Old one still works, but it will become redundant I believe 6 months after it was changed (coming in the next few weeks). The link may still work afterwards, depends when MS next clean up their site.

**Comment by Mytherin** [comment]
Thanks, I updated the readme.
