### ISSUE TITLE
Tibialyzer dont see my server log

### ISSUE THREAD

**Issue by Dejn** [Mytherin/Tibialyzer#50]
Like in Topic :S. Program after update Tibia dont see my server log :(

**Comment by Mytherin** [comment]
Download the [latest version](https://github.com/Mytherin/Tibialyzer/releases/tag/1.2.1) or set your scanning behavior on the **Settings** page to **Scan Entire Memory**.

**Comment by Dejn** [comment]
Ok thx its working :D but i see your screenshoot i wanna make this like you tech me xD
