### ISSUE TITLE
Suggestion: Search Commands

### ISSUE THREAD

**Issue by KuerbisGnu** [Mytherin/Tibialyzer#53]
You added alot new commands that are not shown in the Help Tab.
Would be nice if you can do it and keep it up to date cause it is really useful to handle the large amount of different commands.

**Comment by Mytherin** [comment]
Yes, definitely need to do this. Also need to update the wiki with new tutorials/features because I haven't changed it since 1.0.

**Comment by GalLuvton** [comment]
@KuerbisGnu  Please post it on issue #39 'Todo List'. That was supposed to be the 'suggestion' issue.
