### ISSUE TITLE
Tibializer on Fullscreen

### ISSUE THREAD

**Issue by kical** [Mytherin/Tibialyzer#55]
Ok, So me and mine team are just astonished with your job Mytherin really good job.

I got a issue I'm used to play tibia on full screen, but none loot overlays are working, Dunno if its a Tibia Client Fullscreen DX issue/feature. but anyways I can work without fullscreen.

I'm a bit curious about the HUD functionality, 
DO it reads the Server Log's example:
"Mytherin losses X by a demon"
or reads the in memory program data about the character's HP.

Also The damage@ default view is a Pie diagram its usefull yes but the really one that matters I guess is the details view (in fact an excelent Job). Can in a future Build be reverted these views? I mean detailed view by default and pie view selecting a tab.

applause for this man he needs a beer.

**Comment by kical** [comment]
Hi again So browsing the web I had found this Autohotkey Script

`#SingleInstance, Force

VarSetCapacity(APPBARDATA, A_PtrSize=4 ? 36:48) 
Original_Setting := DllCall("Shell32\SHAppBarMessage"   , "UInt", Msg_ABM_GETSTATE
                                                        , "Ptr", &APPBARDATA
                                                        , "Int")
If (Original_Setting == 2)
{
    New_Setting = 3 
}
ELse If(Original_Setting == 0)
{
    New_Setting = 1
}


;Main Loop
Loop
{
;WinGet, Tibia_PID, PID, Tibia
WinWaitActive, ahk_exe Tibia.exe
Taskbar_Hide()
Loop
{
        WinWaitNotActive, ahk_exe Tibia.exe
        Sleep, 50
    IfWinNotActive, ahk_exe Tibia.exe
    break
}
Taskbar_Restore()
} 

Taskbar_Restore()
{
    global Original_Setting
    global APPBARDATA
    NumPut(Original_Setting, APPBARDATA, A_PtrSize=4 ? 32:40)
    DllCall("Shell32\SHAppBarMessage"   , "UInt", 10 ; ABM_SETSTATE
                                        , "Ptr", &APPBARDATA)
}

Taskbar_Hide()
{
    global New_Setting
    global APPBARDATA
    NumPut(New_Setting, APPBARDATA, A_PtrSize=4 ? 32:40)
    DllCall("Shell32\SHAppBarMessage"   , "UInt", 10 ; ABM_SETSTATE
                                        , "Ptr", &APPBARDATA)
}


^x::ExitApp`

What It does, is that whenever you got TIbia.exe open it will trigger the Autohide Taskbar Function ON and when you open another app ex: chrome it will Turn autohide Off.
It shutdown when pressed (Left CTRL + X)

So it gives me some more pixels to play on tibia somehow fullscreen is.

Tested on Win7 x64.

Could be nice some integration on Tibializer and a bit of improvement.

**Comment by Mytherin** [comment]
> I got a issue I'm used to play tibia on full screen, but none loot overlays are working, Dunno if its a Tibia Client Fullscreen DX issue/feature. but anyways I can work without fullscreen.

Tibialyzer can't work with fullscreen, see [here](https://github.com/Mytherin/Tibialyzer/issues/22) for an explanation why.

> I'm a bit curious about the HUD functionality, 
> DO it reads the Server Log's example:
> "Mytherin losses X by a demon"
> or reads the in memory program data about the character's HP.

The data is read directly from memory, if we were to just go about server log messages we couldn't know the players' starting life, and regeneration isn't shown in the server log either (from food/rings/soft boots); and we couldn't track mana at all, so it would not be possible to accurately obtain the players' life this way.

> Also The damage@ default view is a Pie diagram its usefull yes but the really one that matters I guess is the details view (in fact an excelent Job). Can in a future Build be reverted these views? I mean detailed view by default and pie view selecting a tab.

I could add in an option where you can select the default view for certain notifications; I planned on doing this with creature loot/creature stats already, I could do the same here no problem.

> Could be nice some integration on Tibializer and a bit of improvement.

The script looks good, I might add an option to the AutoHotkey integration to allow users to easily toggle it on/off. I will have to look into it some more. Thanks!

**Comment by Shoax** [comment]
Hey. I got solution for playing tibia on "fullscreen" and using tibialyzer. You just need to download BorderlessWindowed and set it up. It's not exactly fullscreen but it's like Fulscreen Windowed in some games. [Click here](https://www.youtube.com/watch?v=38HK8aiIXzc&) for quick tutorial and download link!

**Comment by CladesAffero** [comment]
i found it related to graphic engine used in tibia. got it working on directX5 but not on directX9 or openGL
