### ISSUE TITLE
No issue - Only contact information

### ISSUE THREAD

**Issue by insectx89** [Mytherin/Tibialyzer#56]
hello

Is there any forum/chat/fb to contact with you mytherin? You are PL?

**Comment by Mytherin** [comment]
You can contact me on [reddit](https://www.reddit.com/user/BadgerBadger8264/). You can also try finding me online on Tibia but I don't play too much; usually for an hour or so in the evenings anywhere between 21:00-23:00 CEST. I'm not Polish, I'm Dutch.
