### ISSUE TITLE
Loot popup not working in flash

### ISSUE THREAD

**Issue by carlxvi** [Mytherin/Tibialyzer#6]
I cant get the tiny loot popup message to work in flash, If i do loot@ it shows what loot has been gained during the hunt, and if I use the premade test message you put in for the necro with BoH it shows up, but if I put a message from my server log in to the test message I get a yellow triangle phrase error. It seems to be the way timestamps is formated cause they go "hour:minute: loot" if I remove the : after minute the messages starts working. But I cant figure out how to make tibialyzer accept the extra : .

Thanks for an amazing program I hope this can be fixed would love to use this alot more!

**Comment by Mytherin** [comment]
Should be fixed with commits ba975ab091cb4f85fb31b2100fcad9fc11e8d849 and 631a6f8285f794b8317625a404b27c905422e89d. I updated the latest release, which you can find [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.1).

**Comment by carlxvi** [comment]
Thanks, Great support!
