### ISSUE TITLE
Easy message identification

### ISSUE THREAD

**Issue by GalLuvton** [Mytherin/Tibialyzer#61]
I don't really know how helpful this might be, but I will share it anyways:
All tibia messages come with IDs (base address + 4) ((base address is the one you add 5c to if you want the next message))
Here is a list of stuff I found so far + internet found for me:
```
MSG_STATUS = 0 -- Status messages (In the screen).
MSG_DEFAULT = 1 -- Any player/npc message in Default channel.
MSG_WHISPER = 2 -- Any player whispering.
MSG_YELL = 3 -- Any player yelling.
MSG_NPC = 6 -- Any NPC answers in NPC channel.
MSG_PVT = 7 -- Private messages from other players.
MSG_CHANNEL = 8 -- Any player message in Guild chat/Game/Help/Real/Tutor/Trade channel
MSG_GC_SERVER = 9 -- server message in Guild chat(logged in, guild motd, etc.)
MSG_GC_VICE = 13 -- guild chat vice
MSG_RED = 16 -- Red alert messages.
MSG_RAID = 17 -- Any white alert message.
MSG_WELCOME = 18 -- Game/Channel welcome messages (ignoring, last visit, helpc channel opening, etc.)
MSG_STATUSLOG = 19 -- Status messages in Server Log (vip logged in / dmg / exp)
MSG_INFO = 20 -- Green messages (loot / look / using / buy) in Server Log.
MSG_SENT = 22 -- Private messages sent by you.
```

Feel free to close this issue if you found no use for this info ;p

**Comment by Javieracost** [comment]
Well I, for one, find it useful. Thank you!

**Comment by Mytherin** [comment]
Cool stuff, but right now I don't have a use for it unfortunately. I already know the difference between server log messages/non-server log messages by the tab they appear in and that's all I need to know as I can identify the other messages from their contents. Thanks for the info, though!
