### ISSUE TITLE
question

### ISSUE THREAD

**Issue by insectx89** [Mytherin/Tibialyzer#63]
How to disable fast and easy a lot of low cost items on loot HUD, for example lowest than 999GP ?

**Comment by Jacu93** [comment]
There is a whole guide about item database configuration. Here you have option to disable low cost items in your profit calculation. Just set "discard value" to the proper value (for example 999). Whole guide is here:
https://github.com/Mytherin/Tibialyzer/wiki/Loot-Management-Guide

**Comment by insectx89** [comment]
thx

**Comment by GalLuvton** [comment]
@insectx89 Please close this issue as it has been addressed
