### ISSUE TITLE
Waste/summary avalanches.

### ISSUE THREAD

**Issue by Elvenpath16** [Mytherin/Tibialyzer#69]
Tibialyzer doesn't count avalanches to my waste. They do pop up in the "used items" sections but are not added to waste. Other runes and potions work fine.
 Screenshot: https://scr.hu/zw2Yed

**Comment by Jacu93** [comment]
I don't get it. 175 gmp + 48 SDs are worth around 26k. Your waste seems to be over 66k so it counts some avalanches... I would say the majority of them. But the accurate value should be around 76k after we add all the avalanches. Something is definitely wrong but not as you described.

**Comment by Elvenpath16** [comment]
Those are ultimate mana potions 350 GP each.

**Comment by Jacu93** [comment]
Sorry then but they look exactly as gmp on this screenshot.

**Comment by Elvenpath16** [comment]
Yea but belive me those are UMP :)

**Comment by KuerbisGnu** [comment]
Check which price you have set for Avalanch runes. It calculates your waste with the price you set at used item. 
item@avalanche rune
![image](https://cloud.githubusercontent.com/assets/17644820/14938916/5a319f40-0f34-11e6-9671-f491e03802ee.png)


Is there 45 at the top right side?

**Comment by Elvenpath16** [comment]
@KuerbisGnu OMG you were right. Idk how did the price changed... Thanks mate :)
