### ISSUE TITLE
Is Tibialyzer working?

### ISSUE THREAD

**Issue by Fmancio** [Mytherin/Tibialyzer#72]
I was not playing tibia in the last days, today I was hunting with some friend and Tibialyzer didn't worked, any part of it. Is this related to some update in Tibia?

**Comment by GalLuvton** [comment]
Tibia updated recently, please download this file and replace it in your tibialyzer folder:
Tibialyzer /Tibialyzer/Database/MemoryAddresses.txt

This should solve your issue.
If solved, please close this ticket

**Comment by Fmancio** [comment]
I've copied the content of this file https://github.com/Mytherin/Tibialyzer/blob/634849d209ceb403abea6a12be33b8fa61f24f94/Tibialyzer/Database/MemoryAddresses.txt
to the correspondent file on tibialyzer folder on my computer. Some parts are working, when i look at items it shows the informations about it, but the curved bars are not working properly, they are always full.

**Comment by kugrjado** [comment]
@Fmancio There're couple of lines missing. This is what it should be look like for Tibialyzer 1.2.2 beta:

```
BootsTypeAddress=0x7752E0
MagicLevelAddress=0x5356C0
RingTypeAddress=0x0
XORAddress=0x5376A0
HealthAddress=0x6D5000
MaxHealthAddress=0x6D502C
ManaAddress=0x5376D0
MaxManaAddress=0x5376A4
LevelAddress=0x5376B8
AmmunitionCountAddress=0x775774
AmmunitionTypeAddress=0x775778
WeaponCountAddress=0x7757F4
WeaponTypeAddress=0x7757F8
ExperienceAddress=0x5376A8
PlayerIDAddress=0x6D5034
BattleListAddress=0x72F6F0
TabsBaseAddress=0x53796C
```

**Comment by Fmancio** [comment]
Actually I'm using tibialyzer 1.2.1. Beta is not working ok here (the curved bars are flickering). I'm testing on 1.2.1 and its working for now. Thanks! =D
