### ISSUE TITLE
Flash client no ss

### ISSUE THREAD

**Issue by Ayshia** [Mytherin/Tibialyzer#78]
Hi, I've been using tibialyzer for few weeks and I realized that it doesnt do screenshoots after an advance. Everything works, except screenshoots I got them enabled and everything is set up correctly but I guess. I checked on tibia client and it works so it doesnt only work for flash client, can u please fix it? : >> Muuuuch lovee

**Comment by Mytherin** [comment]
Should be fixed in the latest beta release, which you can download [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.2.2-beta).
