### ISSUE TITLE
Clarify summary HUD

### ISSUE THREAD

**Issue by mathiasbynens** [Mytherin/Tibialyzer#79]
Suggestion:

- Rename “Loot” to “Loot value (gp)”
- Rename “Waste” to “Supplies used (gp)”
- Add new line with title “Waste (gp)” or “Profit (gp)” (dynamically) with `lootValue - suppliesUsed`
- ~~Format all numbers with grouped thousands, e.g. instead of displaying `12345678` you’d show `12,345,678`~~ (already done in 2c07042113234af3784e90e92af8345e811a9a00)

I think this would be a lot more clear. What do you think?

**Comment by EricArndt** [comment]
Definitely would be nice to have. Including thousands separators would be useful any time numbers need to be displayed.

**Comment by EricArndt** [comment]
To build on this, the grouping should match the system culture. Explicitly calling .ToString("N") on any numeric values that will be displayed to the user should do the trick. Just need to hunt all of them down. [https://msdn.microsoft.com/en-us/library/dwhawy9k.aspx](https://msdn.microsoft.com/en-us/library/dwhawy9k.aspx)

**Comment by mathiasbynens** [comment]
> To build on this, the grouping should match the system culture.

Not sure I agree with that necessarily. The Tibialyzer UI is using the English locale, so IMHO it would make sense for the numbers to be formatted accordingly. Either way it’s no big deal — I’d be fine with `.ToString("N")`.

**Comment by Mytherin** [comment]
Thousand separators are already present in the summary@ and loot@ tab (see 2c07042113234af3784e90e92af8345e811a9a00), are they missing anywhere else that I'm not aware of? I agree with the other suggestions, I will patch them in (or you can do it and send me a pull request).
