### ISSUE TITLE
Problem when selecting to collect no gold coins.

### ISSUE THREAD

**Issue by Fmancio** [Mytherin/Tibialyzer#8]
I play in a master sorcerer, so I don't collect any gold coins in some hunts, but I do collect platinum coins. When I unmark the option to collect the gold coins, the loot don't count any gold, including platinums. There is some way to include all the platinum coins but no gold coins in the loot?

**Comment by Mytherin** [comment]
Should be fixed with commit f63c3b10b83fcaab1568d68a6e7b11a7c84ec62a. I updated the latest release, which you can find [here](https://github.com/Mytherin/Tibialyzer/releases/tag/1.1).
