### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by EricArndt** [Mytherin/Tibialyzer#82]
It's been a little over a month since there has been a release. It would be valuable to at least create a newer beta release so that we can get feedback on the changes. Here's a brief list of what's changed since the last release:

- Lots of HUD and popup improvements
- Performance improvements
- Improved OBS support

**Comment by Mytherin** [comment]
I will create a new beta release, not sure if it makes sense to create a new release as there have not been that many added features. I will probably look at getting Tibialyzer to work with the new client soon, I might do a release when that works.

**Comment by EricArndt** [comment]
The only thing I can see that would be a nice feature is the OBS support. Some of the other stuff would be nice as a patch release.

**Comment by Mytherin** [comment]
I updated the [current beta release](https://github.com/Mytherin/Tibialyzer/releases/tag/1.2.2-beta) with the latest version.

**Comment by EricArndt** [comment]
I'm not seeing a new release. 1.2.2-beta is still listed as the most recent one.

**Comment by mathiasbynens** [comment]
@EricArndt I think Mytherin is saying he created a new ZIP and uploaded it to that same old tag, replacing the old ZIP download for that version.

@Mytherin It’s a bit confusing and generally considered to be a bad practice to re-use version numbers like that. Please consider bumping the version number next time — they’re free and unlimited anyway.

Thank you for the new release!

**Comment by EricArndt** [comment]
@mathiasbynens I was hoping that wasn't what had happened. Like you said, it gets confusing when version numbers are re-used.

**Comment by Mytherin** [comment]
It's a pre-release, not an actual new version, hence why I update the zip file. When the actual release happens I will move on to the next version.

**Comment by Mytherin** [comment]
On that note I will make a new release in a few weeks when Tibia Wikia has gathered images and more information on the new creatures/mounts/etc. introduced in the patch, then I will update the database alongside the new release.

**Comment by mathiasbynens** [comment]
> It's a pre-release, not an actual new version

Pre-releases get a version number and version numbers should only ever refer to a single version. http://semver.org/#spec-item-3

(I apologize for hammering on about this, but I wouldn’t be saying this if I didn’t care about your awesome work on Tibialyzer! ♥)

**Comment by EricArndt** [comment]
@Mytherin It's still confusing. If you get people reporting issues with version 1.2.2, how will you easily be able to tell which one they're using? @mathiasbynens is right. Version numbers are free and shouldn't be re-used. Using something like [semantic versioning](http://semver.org/) is preferrable. Create a 1.2.3-beta if you're just updating the memory locations and 1.3.0-beta if you're releasing everything in master. I'd restore the previous 1.2.2-beta as well to hopefully avoid confusion.

**Comment by Mytherin** [comment]
Alright, I will do it for the next release. I don't feel like updating the current releases, though.
