### ISSUE TITLE
Can u make it work at safari and mac ?

### ISSUE THREAD

**Issue by ancienthorna** [Mytherin/Tibialyzer#86]
I wanted to know if you can fix it to ios and safari ? I would be very happy about it !

**Comment by Mytherin** [comment]
I will likely do some work for OSX if the new standalone client supports OSX, as I am planning on getting a Macbook myself. But currently I'm not planning on supporting the flash client on OSX.

**Comment by ancienthorna** [comment]
Im pretty sure it wont support osx but thanks anyway :s

**Comment by dobakat** [comment]
If the new client supports macOS I will definitely contribute on making it work there :-)

**Comment by ghpabs** [comment]
Is there a new client being released?! Did they mentioned anything about Mac this time? #outoftheloop

**Comment by Javieracost** [comment]
Quoting Mirade:
> it is only planned to support Windows (Windows XP SP3 or newer). You can try running Tibia 11 on other OS, of course, but the client does not officially support them at the moment. Please understand that we cannot make any promises at the moment as to whether or not other OS will be officially supported some time in the future. 

It seems they would be even dropping linux support, so...
