### ISSUE TITLE
Please update Krailos items database

### ISSUE THREAD

**Issue by vinilodeon** [Mytherin/Tibialyzer#87]
Krailos miscellaneous and items are without info (no price, no npc that buy it)

Thanks

**Comment by mathiasbynens** [comment]
@vinilodeon Tibialyzer uses the data from TibiaWiki. Please edit the TibiaWiki pages for the items you’re talking about and it will automatically be fixed in Tibialyzer on the next intake.

**Comment by Vinibi** [comment]
How can I do it, Mathias?

**Comment by KuerbisGnu** [comment]
Which items do you mean exactly? I can do it for you.

**Comment by Vinibi** [comment]
Tibialyzer is not recognizing all new items and new creatures...

**Comment by mathiasbynens** [comment]
For example if Ogre Klubba information is incorrect or missing go to http://tibia.wikia.com/wiki/Ogre_Klubba, click edit, and fix it! Everyone can contribute to the wiki.

**Comment by vinilodeon** [comment]
@mathiasbynens But this information is correct (example)
http://tibia.wikia.com/wiki/Ogre_Nose_Ring
however it's not showing in Tibialyzer who buys this item... just dropped from...
![report](https://cloud.githubusercontent.com/assets/5807332/15801999/8a2aeb7e-2aa6-11e6-99ad-4b0cbd97763c.jpg)

Older items are working well...
![reporte2](https://cloud.githubusercontent.com/assets/5807332/15802012/e1a09ee4-2aa6-11e6-890c-25b971ce97aa.jpg)

Thanks..

**Comment by Mytherin** [comment]
I will perform a new scan and release a new version with the updated database next weekend. If you want, you can manually update your database by running the python scripts in the "Database Scan" folder.
