### ISSUE TITLE
Popup issues v1.2.2 (beta)

### ISSUE THREAD

**Issue by TheLateTes** [Mytherin/Tibialyzer#91]
Whenever I get an Item that I have designated on my Popup Items list my popup looks like.
http://imgur.com/dNyBblY
Though when I use the "Popup Test" button on Tibialyzer it looks as it should
http://imgur.com/en5ViuM
On a slightly different note, fairly often when I am typing in chat I'll get unrecognized commands that will popup.
http://imgur.com/xX911zI

I am using v1.2.2(beta) for Chrome Flash on a Windows 10.

**Comment by Mytherin** [comment]
You can change the popup type in `Settings -> Popup Type`. The type you are using is the `System Popup` which uses the system message. `Popup Test` always uses the Rich Popup. Simply change the setting to `Rich Popup` to also get those popups for regular popups.

The second issue is related to junk in the flash client's memory, I recommend simply disabling popups on unrecognized commands in `Settings -> Popup On Unrecognized Command`.

**Comment by TheLateTes** [comment]
Thank you very much
