### ISSUE TITLE
Summary issue

### ISSUE THREAD

**Issue by bysiek** [Mytherin/Tibialyzer#92]
Hello,
I am using latest released (not-beta) version on flash, and for some reason my summary/loot window drops gets tripled -- meaning:
i kill DL, loot 3 royal spears.
Tibialyzer shows 3 DLs, 9 spears.

update: while writing this post went to rotworms, to test it. Each rotworms counts TWICE.

also command "summary@" is often not recognized

I'd also like to propose "rashid@" command, which would give popup: "Today Rashid is in..." dependent on day.

Regards,
Bysiek

**Comment by Mytherin** [comment]
Duplicate loot on flash is a known issue, I recommend checking `Settings -> Skip Duplicate Loot` and `Settings -> Skip Duplicate Commands` to alleviate the issue.

As for Rashid, you can use the `npc@rashid` command to get his current location.

**Comment by bysiek** [comment]
Thanks, duplicating seems to be working, however I cannot find Skip Duplicate checkbox, any tips?

would you mind pointing me "official" proposition thread, if existing? ;)

As for now, what came to my mind, and wasn't found yet if already has been implemented -- how about "disabling" active window (HUD) -- i.e. "summary" to be visible all the time, but not hideable via LMB excep for maybe classic "x" button? Same thing with multiple visible windows, as i want to check out my experience, it hides my loot etc. if they are "anchorable" -- I can't find the option.(so i suppose it's too hidden)
Regards,

**Comment by Mytherin** [comment]
Recommendations can be posted [here](https://github.com/Mytherin/Tibialyzer/issues/39). You can have multiple visible windows at the same time by setting the Display Group of a notification. You can also change the location on the screen there. This can be done in the Notifications tab.
