### ISSUE TITLE
tibialyzer.exe

### ISSUE THREAD

**Issue by haifay** [Mytherin/Tibialyzer#93]
I'm downloading the zip file. but I'm not finding the tibialyzer.exe

**Comment by Mytherin** [comment]
Maybe you are accidently downloading the source code. The zip file with the executable can be found [here](https://github.com/Mytherin/Tibialyzer/releases/download/1.3.0/Tibialyzer.v1.3.0.zip).

**Comment by haifay** [comment]
thank you

**Comment by haifay** [comment]
now it worked
